development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: mdndata_production
  username: coach
  password: 0708SMClfq!
  socket: /var/run/mysqld/mysqld.sock
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: mdndata_production
  username: coach
  password: 0708SMClfq!
  socket: /var/run/mysqld/mysqld.sock
  pool: 5
  timeout: 5000
